version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Dubai
      PGTZ: Asia/Dubai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fastapi_network
    command: ["postgres", "-c", "timezone=Asia/Dubai"]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    env_file:
      - .env.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - fastapi_network

volumes:
  pgdata:

networks:
  fastapi_network:
    external: true
