version: "3.8"

services:
  redis:
    image: redis:7
    container_name: fastapi-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fastapi_network

  celery-worker:
    build:
      context: .
    container_name: celery-worker
    command: >
      /bin/bash -c "celery -A app.main.celery worker -l info -Q auth-queue -n worker-auth@%h & celery -A app.main.celery worker --loglevel=info -Q user-queue -n worker-user@%h"
    env_file: .env
    volumes:
      - .:/code
    networks:
      - fastapi_network
    depends_on:
      - redis
    healthcheck:
      disable: true

  celery-beat:
    build:
      context: .
    container_name: celery-beat
    command: celery -A app.main.celery beat --loglevel=info --scheduler celery.beat:PersistentScheduler
    env_file: .env
    volumes:
      - .:/code
    networks:
      - fastapi_network
    depends_on:
      - redis
    healthcheck:
      disable: true

  flower:
    image: mher/flower
    container_name: flower
    env_file: .env
    environment:
      - FLOWER_BROKER=${CELERY_BROKER_URL}
    ports:
      - "5555:5555"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    external: true
