version: "3.8"

services:
  celery-worker:
    build:
      context: .
    container_name: celery-worker
    command: celery -A app.integrations.celery_app.celery_app worker --loglevel=info
    env_file: .env
    volumes:
      - .:/code
    networks:
      - fastapi_network
    healthcheck:
      disable: true

  celery-beat:
    build:
      context: .
    container_name: celery-beat
    command: celery -A app.integrations.celery_app.celery_app beat --loglevel=info --scheduler celery.beat:PersistentScheduler
    env_file: .env
    volumes:
      - .:/code
    networks:
      - fastapi_network
    healthcheck:
      disable: true

  flower:
    image: mher/flower:2.0.1
    container_name: flower
    environment:
      - FLOWER_BROKER=redis://${REDIS_HOST}:${REDIS_PORT}
      - FLOWER_PORT=5555
    env_file: .env
    ports:
      - "5555:5555"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    external: true
