version: "3.8"

services:
  celery-worker:
    build:
      context: .
    container_name: celery-worker
    command: celery -A app.integrations.celery_app.celery_app worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - db
    volumes:
      - .:/code
    networks:
      - fastapi_network

  celery-beat:
    build:
      context: .
    container_name: celery-beat
    command: celery -A app.integrations.celery_app.celery_app beat --loglevel=info --scheduler celery.beat:PersistentScheduler
    env_file: .env
    depends_on:
      - redis
      - db
    volumes:
      - .:/code
    networks:
      - fastapi_network

  flower:
    image: mher/flower:2.0.1
    container_name: flower
    command: flower --broker=${CELERY_BROKER_URL} --port=5555
    env_file: .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - fastapi_network

networks:
  fastapi_network:
    external: true
