version: "3.8"

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=debug
    command: >
      sh -c "if [ \"$ENVIRONMENT\" = \"dev\" ]; then \
        uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-level debug --reload-dir /code; \
        else uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug; fi"
    volumes:
      - .:/code
    networks:
      - fastapi_network

  redis:
    image: redis:7
    container_name: fastapi-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
    external: true
