version: "3.8"

services:
  celery-worker:
    build:
      context: .
    container_name: celery-worker
    command: celery -A app.integrations.celery_app.celery_app worker --loglevel=info -Q auth-queue,user-queue
    env_file: .env
    volumes:
      - .:/code
    networks:
      - fastapi_network
    healthcheck:
      disable: true

  celery-beat:
    build:
      context: .
    container_name: celery-beat
    command: celery -A app.integrations.celery_app.celery_app beat --loglevel=info --scheduler celery.beat:PersistentScheduler
    env_file: .env
    volumes:
      - .:/code
    networks:
      - fastapi_network
    healthcheck:
      disable: true

  flower:
    image: mher/flower
    container_name: flower
    env_file: .env
    environment:
      - FLOWER_BROKER=${CELERY_BROKER_URL}
    ports:
      - "5555:5555"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    external: true
