"""Remove is_active from access_tokens and refresh_tokens

Revision ID: 660b20015a35
Revises: 3b45f648a90e
Create Date: 2025-07-08 14:25:48.817799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '660b20015a35'
down_revision: Union[str, None] = '3b45f648a90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_tokens', 'is_active')
    op.drop_column('refresh_tokens', 'is_active')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'refresh_tokens',
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        'access_tokens',
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
