"""initial tables and token relations

Revision ID: 8a5e1cfa8586
Revises: 
Create Date: 2025-07-08 10:33:06.856696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a5e1cfa8586'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        comment='Stores role and permission information.'
    )
    op.create_index(
        op.f('ix_roles_id'), 'roles', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_roles_name'), 'roles', ['name'], unique=True
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='Stores user information.'
    )
    op.create_index(
        op.f('ix_users_email'), 'users', ['email'], unique=True
    )
    op.create_index(
        op.f('ix_users_id'), 'users', ['id'], unique=False
    )
    op.create_table(
        'access_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False
        ),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_access_tokens_id'), 'access_tokens', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_access_tokens_token'), 'access_tokens', ['token'], unique=True
    )
    op.create_index(
        op.f('ix_access_tokens_user_id'), 'access_tokens', ['user_id'], unique=False
    )
    op.create_table(
        'refresh_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('access_token_id', sa.Integer(), nullable=True),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False
        ),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['access_token_id'], ['access_tokens.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_refresh_tokens_access_token_id'),
        'refresh_tokens', ['access_token_id'], unique=False
    )
    op.create_index(
        op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True
    )
    op.create_index(
        op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens'
    )
    op.drop_index(
        op.f('ix_refresh_tokens_token'), table_name='refresh_tokens'
    )
    op.drop_index(
        op.f('ix_refresh_tokens_id'), table_name='refresh_tokens'
    )
    op.drop_index(
        op.f('ix_refresh_tokens_access_token_id'),
        table_name='refresh_tokens'
    )
    op.drop_table('refresh_tokens')
    op.drop_index(
        op.f('ix_access_tokens_user_id'), table_name='access_tokens'
    )
    op.drop_index(
        op.f('ix_access_tokens_token'), table_name='access_tokens'
    )
    op.drop_index(
        op.f('ix_access_tokens_id'), table_name='access_tokens'
    )
    op.drop_table('access_tokens')
    op.drop_index(
        op.f('ix_users_id'), table_name='users'
    )
    op.drop_index(
        op.f('ix_users_email'), table_name='users'
    )
    op.drop_table('users')
    op.drop_index(
        op.f('ix_roles_name'), table_name='roles'
    )
    op.drop_index(
        op.f('ix_roles_id'), table_name='roles'
    )
    op.drop_table('roles')
    # ### end Alembic commands ###
